version: '3'

services:

  # Config Service
  config-service:
    build: config-service
    image: config-service-image:latest
    ports:
      - "8081:8081"

  # Discovery Service
  discovery-service:
    build: discovery-service
    image: discovery-service-image:latest
    ports:
      - "8761:8761"
    depends_on:
      - config-service

    # Gateway Service
  gateway-service:
    build: gateway-service
    image: gateway-service-image:latest
    ports:
      - "8080:8080"
    depends_on:
      - config-service
      - discovery-service

  # PostgreSQL Database
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: microservices
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_password
    ports:
      - "5432:5432"

  # Main Service (sum-calculator-service)
  sum-calculator-service:
    image: sum-calculator-service-image:latest
    ports:
      - "9090:9090"
    depends_on:
      - config-service
      - discovery-service
      - gateway-service
      - postgres

  # Percentage Service
  # percentage-service:
  #  image: percentage-service-image:latest
  #  ports:
  #    - "7070:7070"
  #  depends_on:
  #    - config-service
  #    - discovery-service
  #    - gateway-service