server:
  port: 8080

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://discovery-service:8761/eureka
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: sum-calculator-service
          uri: lb://sum-calculator-service
          predicates:
            - Path=/sumCalculator/**
        - id: percentage-service
          uri: lb://percentage-service
          predicates:
            - Path=/percentage/**